# Generated by Django 4.0.3 on 2022-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LG', 'Language'), ('TP', 'Topic')], default='LG', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
            ],
        ),
    ]
